//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeamSorting.Lang {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources_cs_CZ {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources_cs_CZ() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TeamSorting.Lang.Resources.cs-CZ", typeof(Resources_cs_CZ).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ne.
        /// </summary>
        public static string Bool_False {
            get {
                return ResourceManager.GetString("Bool_False", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ano.
        /// </summary>
        public static string Bool_True {
            get {
                return ResourceManager.GetString("Bool_True", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sloupec.
        /// </summary>
        public static string CsvErrorDialog_Grid_ColumnNumber_Header {
            get {
                return ResourceManager.GetString("CsvErrorDialog_Grid_ColumnNumber_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chyba.
        /// </summary>
        public static string CsvErrorDialog_Grid_Error_Header {
            get {
                return ResourceManager.GetString("CsvErrorDialog_Grid_Error_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Řádek.
        /// </summary>
        public static string CsvErrorDialog_Grid_RowNumber_Header {
            get {
                return ResourceManager.GetString("CsvErrorDialog_Grid_RowNumber_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string CsvErrorDialog_Ok_Button {
            get {
                return ResourceManager.GetString("CsvErrorDialog_Ok_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chyba při načítání dat z CSV.
        /// </summary>
        public static string CsvErrorDialog_Title {
            get {
                return ResourceManager.GetString("CsvErrorDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chyba čtení dat ze souboru.
        /// </summary>
        public static string Data_LoadFromFile_Error {
            get {
                return ResourceManager.GetString("Data_LoadFromFile_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data ze souboru úspěšně načtena.
        /// </summary>
        public static string Data_LoadFromFile_Success {
            get {
                return ResourceManager.GetString("Data_LoadFromFile_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chyba čtení hodnoty záznamu disciplíny.
        /// </summary>
        public static string Data_LoadMembersData_DisciplineRecord_UnknownError {
            get {
                return ResourceManager.GetString("Data_LoadMembersData_DisciplineRecord_UnknownError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Člen se jménem {0} již existuje..
        /// </summary>
        public static string Data_LoadMembersData_DuplicateMemberNames_Error {
            get {
                return ResourceManager.GetString("Data_LoadMembersData_DuplicateMemberNames_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nalezen duplicitní člen v podmínkách kombinací členů.
        /// </summary>
        public static string Data_LoadMembersData_DuplicateMembersInConstarins_Warning {
            get {
                return ResourceManager.GetString("Data_LoadMembersData_DuplicateMembersInConstarins_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nalezeno prázné jméno..
        /// </summary>
        public static string Data_LoadMembersData_EmptyMemberName_Error {
            get {
                return ResourceManager.GetString("Data_LoadMembersData_EmptyMemberName_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nalezeni neznámí členové v podmínkách kombinací členů: {0}.
        /// </summary>
        public static string Data_LoadMembersData_UnknownMemberInConstrains_Error {
            get {
                return ResourceManager.GetString("Data_LoadMembersData_UnknownMemberInConstrains_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chybný formát hodnoty záznamu disciplíny.
        ///Očekávaný formát je {0}.
        /// </summary>
        public static string Data_LoadMembersData_WrongDisciplineRecordFormat_Error {
            get {
                return ResourceManager.GetString("Data_LoadMembersData_WrongDisciplineRecordFormat_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chyba čtení datového typu disciplíny {0}.
        /// </summary>
        public static string Data_ReadDisciplineDataTypes_ReadingError {
            get {
                return ResourceManager.GetString("Data_ReadDisciplineDataTypes_ReadingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neznámý datový typ &apos;{0}&apos; disciplíny &apos;{1}&apos;
        ///Platné hodnoty: {2}.
        /// </summary>
        public static string Data_ReadDisciplineDataTypes_WrongDisciplineDataTypes_Error {
            get {
                return ResourceManager.GetString("Data_ReadDisciplineDataTypes_WrongDisciplineDataTypes_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neznámé řazení &apos;{0}&apos; disciplíny &apos;{1}&apos;
        ///Platné hodnoty: {2}.
        /// </summary>
        public static string Data_ReadDisciplineSortTypes_WrongDisciplineSortOrder_Error {
            get {
                return ResourceManager.GetString("Data_ReadDisciplineSortTypes_WrongDisciplineSortOrder_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tým{0}.
        /// </summary>
        public static string Data_TeamName_Template {
            get {
                return ResourceManager.GetString("Data_TeamName_Template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nezařazení.
        /// </summary>
        public static string Data_TeamName_Unsorted {
            get {
                return ResourceManager.GetString("Data_TeamName_Unsorted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hlavička obsahuje duplicitní sloupce: .
        /// </summary>
        public static string Data_ValidateCsvHeader_DuplicateColumns_Error {
            get {
                return ResourceManager.GetString("Data_ValidateCsvHeader_DuplicateColumns_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hlavička neobsahuje následující sloupce: .
        /// </summary>
        public static string Data_ValidateCsvHeader_MissingColumns_Error {
            get {
                return ResourceManager.GetString("Data_ValidateCsvHeader_MissingColumns_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Priorita.
        /// </summary>
        public static string DisciplineInfo_Priority {
            get {
                return ResourceManager.GetString("DisciplineInfo_Priority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Číslo.
        /// </summary>
        public static string Enum_DisciplineDataType_Number {
            get {
                return ResourceManager.GetString("Enum_DisciplineDataType_Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Čas.
        /// </summary>
        public static string Enum_DisciplineDataType_Time {
            get {
                return ResourceManager.GetString("Enum_DisciplineDataType_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vzestupně.
        /// </summary>
        public static string Enum_SortOrder_Asc {
            get {
                return ResourceManager.GetString("Enum_SortOrder_Asc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sestupně.
        /// </summary>
        public static string Enum_SortOrder_Desc {
            get {
                return ResourceManager.GetString("Enum_SortOrder_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Přidat disciplínu.
        /// </summary>
        public static string InputView_AddDiscipline_Button {
            get {
                return ResourceManager.GetString("InputView_AddDiscipline_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jméno.
        /// </summary>
        public static string InputView_DataGrid_ColumnHeader_Name {
            get {
                return ResourceManager.GetString("InputView_DataGrid_ColumnHeader_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nesmí být s.
        /// </summary>
        public static string InputView_DataGrid_ColumnHeader_NotWith {
            get {
                return ResourceManager.GetString("InputView_DataGrid_ColumnHeader_NotWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Musí být s.
        /// </summary>
        public static string InputView_DataGrid_ColumnHeader_With {
            get {
                return ResourceManager.GetString("InputView_DataGrid_ColumnHeader_With", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smazat data.
        /// </summary>
        public static string InputView_DeleteData_Button {
            get {
                return ResourceManager.GetString("InputView_DeleteData_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zrušit.
        /// </summary>
        public static string InputView_DeleteData_WarningDialog_Cancel {
            get {
                return ResourceManager.GetString("InputView_DeleteData_WarningDialog_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smazat.
        /// </summary>
        public static string InputView_DeleteData_WarningDialog_Delete {
            get {
                return ResourceManager.GetString("InputView_DeleteData_WarningDialog_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Všechna data budou smazána (členové, týmy, disciplíny). 
        ///Chcete pokračovat?.
        /// </summary>
        public static string InputView_DeleteData_WarningDialog_Message {
            get {
                return ResourceManager.GetString("InputView_DeleteData_WarningDialog_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Načíst data.
        /// </summary>
        public static string InputView_LoadData_Button {
            get {
                return ResourceManager.GetString("InputView_LoadData_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Načíst ze souboru.
        /// </summary>
        public static string InputView_LoadData_FileDialog {
            get {
                return ResourceManager.GetString("InputView_LoadData_FileDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Člen se stejným jménem již existuje.
        /// </summary>
        public static string InputView_Member_DuplicateName_Error {
            get {
                return ResourceManager.GetString("InputView_Member_DuplicateName_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jméno nemůže být prázdné.
        /// </summary>
        public static string InputView_Member_EmptyName_Error {
            get {
                return ResourceManager.GetString("InputView_Member_EmptyName_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Název disciplíny.
        /// </summary>
        public static string InputView_NewDiscipline_Watermark {
            get {
                return ResourceManager.GetString("InputView_NewDiscipline_Watermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Přidat člena.
        /// </summary>
        public static string InputView_NewMember_Button {
            get {
                return ResourceManager.GetString("InputView_NewMember_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jméno.
        /// </summary>
        public static string InputView_NewMember_TextBox_Watermark {
            get {
                return ResourceManager.GetString("InputView_NewMember_TextBox_Watermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odstranit disciplínu.
        /// </summary>
        public static string InputView_RemoveDiscipline_Button {
            get {
                return ResourceManager.GetString("InputView_RemoveDiscipline_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odstranit člena.
        /// </summary>
        public static string InputView_RemoveMember_Button_Tooltip {
            get {
                return ResourceManager.GetString("InputView_RemoveMember_Button_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Semínko.
        /// </summary>
        public static string InputView_Seed_Watermark {
            get {
                return ResourceManager.GetString("InputView_Seed_Watermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zobrazit týmy.
        /// </summary>
        public static string InputView_ShowTeams_Button {
            get {
                return ResourceManager.GetString("InputView_ShowTeams_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zrušit.
        /// </summary>
        public static string InputView_Sort_WarningDialog_Cancel {
            get {
                return ResourceManager.GetString("InputView_Sort_WarningDialog_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smazat.
        /// </summary>
        public static string InputView_Sort_WarningDialog_Delete {
            get {
                return ResourceManager.GetString("InputView_Sort_WarningDialog_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Všechny týmy budou smazány a nahrazeny novými.
        ///Chcete smazat stávající týmy?.
        /// </summary>
        public static string InputView_Sort_WarningDialog_Message {
            get {
                return ResourceManager.GetString("InputView_Sort_WarningDialog_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rozdělit do týmů.
        /// </summary>
        public static string InputView_SortToTeams_Button {
            get {
                return ResourceManager.GetString("InputView_SortToTeams_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hledat.
        /// </summary>
        public static string MemberListSelection_Search {
            get {
                return ResourceManager.GetString("MemberListSelection_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Probíhá rozřazení....
        /// </summary>
        public static string Sorting_ProgressText {
            get {
                return ResourceManager.GetString("Sorting_ProgressText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Přidat tým.
        /// </summary>
        public static string TeamsView_AddTeam_Button {
            get {
                return ResourceManager.GetString("TeamsView_AddTeam_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zpět.
        /// </summary>
        public static string TeamsView_Back_Button {
            get {
                return ResourceManager.GetString("TeamsView_Back_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Členové.
        /// </summary>
        public static string TeamsView_ControlsSection_Members {
            get {
                return ResourceManager.GetString("TeamsView_ControlsSection_Members", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Řazení.
        /// </summary>
        public static string TeamsView_ControlsSection_Sorting {
            get {
                return ResourceManager.GetString("TeamsView_ControlsSection_Sorting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Týmy.
        /// </summary>
        public static string TeamsView_ControlsSection_Teams {
            get {
                return ResourceManager.GetString("TeamsView_ControlsSection_Teams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vytvořit novou kombinaci.
        /// </summary>
        public static string TeamsView_CreateNewCombination_Button {
            get {
                return ResourceManager.GetString("TeamsView_CreateNewCombination_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chyba při ukládání souboru:
        ///{0}.
        /// </summary>
        public static string TeamsView_CsvExport_Error {
            get {
                return ResourceManager.GetString("TeamsView_CsvExport_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soubor byl úspěšně uložen..
        /// </summary>
        public static string TeamsView_CsvExport_Success {
            get {
                return ResourceManager.GetString("TeamsView_CsvExport_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rozdíly mezi týmy:.
        /// </summary>
        public static string TeamsView_Differences_Label {
            get {
                return ResourceManager.GetString("TeamsView_Differences_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Průměry disciplín:.
        /// </summary>
        public static string TeamsView_DisciplineAverages_Label {
            get {
                return ResourceManager.GetString("TeamsView_DisciplineAverages_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exportovat týmy do CSV.
        /// </summary>
        public static string TeamsView_ExportTeamsToCsv_FileDialogTitle {
            get {
                return ResourceManager.GetString("TeamsView_ExportTeamsToCsv_FileDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exportovat týmy do CSV.
        /// </summary>
        public static string TeamsView_ExportToCSV_Button {
            get {
                return ResourceManager.GetString("TeamsView_ExportToCSV_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zakázat změnu týmu.
        /// </summary>
        public static string TeamsView_MemberCard_PinMember {
            get {
                return ResourceManager.GetString("TeamsView_MemberCard_PinMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Povolit změnu týmu.
        /// </summary>
        public static string TeamsView_MemberCard_UnpinMember {
            get {
                return ResourceManager.GetString("TeamsView_MemberCard_UnpinMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Člen **{0}** přesunut z týmu **{1}** do týmu **{2}**..
        /// </summary>
        public static string TeamsView_MemberMoved_Message {
            get {
                return ResourceManager.GetString("TeamsView_MemberMoved_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zakázat změnu týmu.
        /// </summary>
        public static string TeamsView_PinMembers_Label {
            get {
                return ResourceManager.GetString("TeamsView_PinMembers_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Semínko.
        /// </summary>
        public static string TeamsView_Seed_Label {
            get {
                return ResourceManager.GetString("TeamsView_Seed_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zobrazit detaily členů.
        /// </summary>
        public static string TeamsView_ShowMemberDetails_Label {
            get {
                return ResourceManager.GetString("TeamsView_ShowMemberDetails_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seřadit podle jména.
        /// </summary>
        public static string TeamsView_SortByMemberName_Label {
            get {
                return ResourceManager.GetString("TeamsView_SortByMemberName_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rozřadit zbývající členy.
        /// </summary>
        public static string TeamsView_SortRestOfMembers_Button {
            get {
                return ResourceManager.GetString("TeamsView_SortRestOfMembers_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tým je platný: {0}.
        /// </summary>
        public static string TeamsView_TeamIsValid_ToolTip {
            get {
                return ResourceManager.GetString("TeamsView_TeamIsValid_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zrušit.
        /// </summary>
        public static string WarningDialog_Cancel_Button {
            get {
                return ResourceManager.GetString("WarningDialog_Cancel_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pokračovat.
        /// </summary>
        public static string WarningDialog_Confirm_Button {
            get {
                return ResourceManager.GetString("WarningDialog_Confirm_Button", resourceCulture);
            }
        }
    }
}
