//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeamSorting.Lang {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("TeamSorting.Lang.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string InputView_LoadData_FileDialog {
            get {
                return ResourceManager.GetString("InputView_LoadData_FileDialog", resourceCulture);
            }
        }
        
        public static string InputView_RemoveDiscipline_Button {
            get {
                return ResourceManager.GetString("InputView_RemoveDiscipline_Button", resourceCulture);
            }
        }
        
        public static string TeamsView_Sort_WarningDialog_Message {
            get {
                return ResourceManager.GetString("TeamsView_Sort_WarningDialog_Message", resourceCulture);
            }
        }
        
        public static string TeamsView_ExportTeamsToCsv_FileDialogTitle {
            get {
                return ResourceManager.GetString("TeamsView_ExportTeamsToCsv_FileDialogTitle", resourceCulture);
            }
        }
        
        public static string InputView_NewDiscipline_Watermark {
            get {
                return ResourceManager.GetString("InputView_NewDiscipline_Watermark", resourceCulture);
            }
        }
        
        public static string InputView_AddDiscipline_Button {
            get {
                return ResourceManager.GetString("InputView_AddDiscipline_Button", resourceCulture);
            }
        }

        public static string InputView_DuplicateDiscipline_Error {
            get { return ResourceManager.GetString("InputView_DuplicateDiscipline_Error", resourceCulture); }
        }
        
        public static string TeamsView_Seed_Watermark {
            get {
                return ResourceManager.GetString("TeamsView_Seed_Watermark", resourceCulture);
            }
        }
        
        public static string InputView_RemoveMember_Button_Tooltip {
            get {
                return ResourceManager.GetString("InputView_RemoveMember_Button_Tooltip", resourceCulture);
            }
        }
        
        public static string InputView_DataGrid_ColumnHeader_Name {
            get {
                return ResourceManager.GetString("InputView_DataGrid_ColumnHeader_Name", resourceCulture);
            }
        }
        
        public static string InputView_DataGrid_ColumnHeader_With {
            get {
                return ResourceManager.GetString("InputView_DataGrid_ColumnHeader_With", resourceCulture);
            }
        }
        
        public static string InputView_DataGrid_ColumnHeader_NotWith {
            get {
                return ResourceManager.GetString("InputView_DataGrid_ColumnHeader_NotWith", resourceCulture);
            }
        }
        
        public static string InputView_NewMember_TextBox_Watermark {
            get {
                return ResourceManager.GetString("InputView_NewMember_TextBox_Watermark", resourceCulture);
            }
        }
        
        public static string InputView_NewMember_Button {
            get {
                return ResourceManager.GetString("InputView_NewMember_Button", resourceCulture);
            }
        }
        
        public static string InputView_LoadData_Button {
            get {
                return ResourceManager.GetString("InputView_LoadData_Button", resourceCulture);
            }
        }
        
        public static string TeamsView_Back_Button {
            get {
                return ResourceManager.GetString("TeamsView_Back_Button", resourceCulture);
            }
        }
        
        public static string TeamsView_ExportToCSV_Button {
            get {
                return ResourceManager.GetString("TeamsView_ExportToCSV_Button", resourceCulture);
            }
        }
        
        public static string TeamsView_ShowMemberDetails_Label {
            get {
                return ResourceManager.GetString("TeamsView_ShowMemberDetails_Label", resourceCulture);
            }
        }
        
        public static string TeamsView_Differences_Label {
            get {
                return ResourceManager.GetString("TeamsView_Differences_Label", resourceCulture);
            }
        }
        
        public static string TeamsView_Seed_Label {
            get {
                return ResourceManager.GetString("TeamsView_Seed_Label", resourceCulture);
            }
        }
        
        public static string Data_TeamName_Template {
            get {
                return ResourceManager.GetString("Data_TeamName_Template", resourceCulture);
            }
        }
        
        public static string WarningDialog_Cancel_Button {
            get {
                return ResourceManager.GetString("WarningDialog_Cancel_Button", resourceCulture);
            }
        }
        
        public static string WarningDialog_Confirm_Button {
            get {
                return ResourceManager.GetString("WarningDialog_Confirm_Button", resourceCulture);
            }
        }
        
        public static string Enum_DisciplineDataType_Number {
            get {
                return ResourceManager.GetString("Enum_DisciplineDataType_Number", resourceCulture);
            }
        }
        
        public static string Enum_DisciplineDataType_Time {
            get {
                return ResourceManager.GetString("Enum_DisciplineDataType_Time", resourceCulture);
            }
        }
        
        public static string Enum_SortOrder_Asc {
            get {
                return ResourceManager.GetString("Enum_SortOrder_Asc", resourceCulture);
            }
        }
        
        public static string Enum_SortOrder_Desc {
            get {
                return ResourceManager.GetString("Enum_SortOrder_Desc", resourceCulture);
            }
        }
        
        public static string Bool_True {
            get {
                return ResourceManager.GetString("Bool_True", resourceCulture);
            }
        }
        
        public static string Bool_False {
            get {
                return ResourceManager.GetString("Bool_False", resourceCulture);
            }
        }
        
        public static string Data_LoadFromFile_Error {
            get {
                return ResourceManager.GetString("Data_LoadFromFile_Error", resourceCulture);
            }
        }
        
        public static string Data_ValidateCsvHeader_MissingColumns_Error {
            get {
                return ResourceManager.GetString("Data_ValidateCsvHeader_MissingColumns_Error", resourceCulture);
            }
        }
        
        public static string Data_ValidateCsvHeader_DuplicateColumns_Error {
            get {
                return ResourceManager.GetString("Data_ValidateCsvHeader_DuplicateColumns_Error", resourceCulture);
            }
        }
        
        public static string Data_ReadDisciplineDataTypes_WrongDisciplineDataTypes_Error {
            get {
                return ResourceManager.GetString("Data_ReadDisciplineDataTypes_WrongDisciplineDataTypes_Error", resourceCulture);
            }
        }
        
        public static string Data_ReadDisciplineDataTypes_ReadingError {
            get {
                return ResourceManager.GetString("Data_ReadDisciplineDataTypes_ReadingError", resourceCulture);
            }
        }
        
        public static string Data_ReadDisciplineSortTypes_WrongDisciplineSortOrder_Error {
            get {
                return ResourceManager.GetString("Data_ReadDisciplineSortTypes_WrongDisciplineSortOrder_Error", resourceCulture);
            }
        }
        
        public static string Data_LoadMembersData_DuplicateMemberNames_Error {
            get {
                return ResourceManager.GetString("Data_LoadMembersData_DuplicateMemberNames_Error", resourceCulture);
            }
        }
        
        public static string Data_LoadMembersData_UnknownMemberInConstrains_Error {
            get {
                return ResourceManager.GetString("Data_LoadMembersData_UnknownMemberInConstrains_Error", resourceCulture);
            }
        }
        
        public static string Data_LoadMembersData_WrongDisciplineRecordFormat_Error {
            get {
                return ResourceManager.GetString("Data_LoadMembersData_WrongDisciplineRecordFormat_Error", resourceCulture);
            }
        }
        
        public static string Data_LoadMembersData_DisciplineRecord_UnknownError {
            get {
                return ResourceManager.GetString("Data_LoadMembersData_DisciplineRecord_UnknownError", resourceCulture);
            }
        }
        
        public static string CsvErrorDialog_Ok_Button {
            get {
                return ResourceManager.GetString("CsvErrorDialog_Ok_Button", resourceCulture);
            }
        }
        
        public static string CsvErrorDialog_Title {
            get {
                return ResourceManager.GetString("CsvErrorDialog_Title", resourceCulture);
            }
        }
        
        public static string Data_LoadMembersData_EmptyMemberName_Error {
            get {
                return ResourceManager.GetString("Data_LoadMembersData_EmptyMemberName_Error", resourceCulture);
            }
        }
        
        public static string CsvErrorDialog_Grid_RowNumber_Header {
            get {
                return ResourceManager.GetString("CsvErrorDialog_Grid_RowNumber_Header", resourceCulture);
            }
        }
        
        public static string CsvErrorDialog_Grid_ColumnNumber_Header {
            get {
                return ResourceManager.GetString("CsvErrorDialog_Grid_ColumnNumber_Header", resourceCulture);
            }
        }
        
        public static string CsvErrorDialog_Grid_Error_Header {
            get {
                return ResourceManager.GetString("CsvErrorDialog_Grid_Error_Header", resourceCulture);
            }
        }
        
        public static string TeamsView_ControlsSection_Sorting {
            get {
                return ResourceManager.GetString("TeamsView_ControlsSection_Sorting", resourceCulture);
            }
        }
        
        public static string TeamsView_CsvExport_Success {
            get {
                return ResourceManager.GetString("TeamsView_CsvExport_Success", resourceCulture);
            }
        }
        
        public static string TeamsView_CsvExport_Error {
            get {
                return ResourceManager.GetString("TeamsView_CsvExport_Error", resourceCulture);
            }
        }
        
        public static string InputView_ShowTeams_Button {
            get {
                return ResourceManager.GetString("InputView_ShowTeams_Button", resourceCulture);
            }
        }
        
        public static string TeamsView_Sort_WarningDialog_Cancel {
            get {
                return ResourceManager.GetString("TeamsView_Sort_WarningDialog_Cancel", resourceCulture);
            }
        }
        
        public static string TeamsView_Sort_WarningDialog_Delete {
            get {
                return ResourceManager.GetString("TeamsView_Sort_WarningDialog_Delete", resourceCulture);
            }
        }
        
        public static string InputView_DeleteData_WarningDialog_Message {
            get {
                return ResourceManager.GetString("InputView_DeleteData_WarningDialog_Message", resourceCulture);
            }
        }
        
        public static string InputView_DeleteData_WarningDialog_Cancel {
            get {
                return ResourceManager.GetString("InputView_DeleteData_WarningDialog_Cancel", resourceCulture);
            }
        }
        
        public static string InputView_DeleteData_WarningDialog_Delete {
            get {
                return ResourceManager.GetString("InputView_DeleteData_WarningDialog_Delete", resourceCulture);
            }
        }
        
        public static string MemberListSelection_Search {
            get {
                return ResourceManager.GetString("MemberListSelection_Search", resourceCulture);
            }
        }
        
        public static string InputView_Member_EmptyName_Error {
            get {
                return ResourceManager.GetString("InputView_Member_EmptyName_Error", resourceCulture);
            }
        }
        
        public static string InputView_Member_DuplicateName_Error {
            get {
                return ResourceManager.GetString("InputView_Member_DuplicateName_Error", resourceCulture);
            }
        }
        
        public static string TeamsView_MemberMoved_Message {
            get {
                return ResourceManager.GetString("TeamsView_MemberMoved_Message", resourceCulture);
            }
        }
        
        public static string Data_TeamName_Unsorted {
            get {
                return ResourceManager.GetString("Data_TeamName_Unsorted", resourceCulture);
            }
        }
        
        public static string TeamsView_AddTeam_Button {
            get {
                return ResourceManager.GetString("TeamsView_AddTeam_Button", resourceCulture);
            }
        }
        
        public static string InputView_DeleteData_Button {
            get {
                return ResourceManager.GetString("InputView_DeleteData_Button", resourceCulture);
            }
        }
        
        public static string TeamsView_NewCombination_Button {
            get {
                return ResourceManager.GetString("TeamsView_NewCombination_Button", resourceCulture);
            }
        }
        
        public static string Sorting_ProgressText {
            get {
                return ResourceManager.GetString("Sorting_ProgressText", resourceCulture);
            }
        }
        
        public static string TeamsView_DisciplineAverages_Label {
            get {
                return ResourceManager.GetString("TeamsView_DisciplineAverages_Label", resourceCulture);
            }
        }
        
        public static string DisciplineInfo_Priority {
            get {
                return ResourceManager.GetString("DisciplineInfo_Priority", resourceCulture);
            }
        }
        
        public static string Data_ValidateCsvHeader_MissingHeader {
            get {
                return ResourceManager.GetString("Data_ValidateCsvHeader_MissingHeader", resourceCulture);
            }
        }
        
        public static string TeamsView_MemberCard_PinMember {
            get {
                return ResourceManager.GetString("TeamsView_MemberCard_PinMember", resourceCulture);
            }
        }
        
        public static string TeamsView_MemberCard_UnpinMember {
            get {
                return ResourceManager.GetString("TeamsView_MemberCard_UnpinMember", resourceCulture);
            }
        }
        
        public static string TeamsView_PinMembers_Label {
            get {
                return ResourceManager.GetString("TeamsView_PinMembers_Label", resourceCulture);
            }
        }
        
        public static string TeamsView_ControlsSection_Members {
            get {
                return ResourceManager.GetString("TeamsView_ControlsSection_Members", resourceCulture);
            }
        }
        
        public static string TeamsView_ControlsSection_Teams {
            get {
                return ResourceManager.GetString("TeamsView_ControlsSection_Teams", resourceCulture);
            }
        }
        
        public static string TeamsView_NewCombination_ToolTip {
            get {
                return ResourceManager.GetString("TeamsView_NewCombination_ToolTip", resourceCulture);
            }
        }
        
        public static string TeamsView_DeleteTeam_Tooltip {
            get {
                return ResourceManager.GetString("TeamsView_DeleteTeam_Tooltip", resourceCulture);
            }
        }
        
        public static string MainWindow_NewVersion_Download_Button {
            get {
                return ResourceManager.GetString("MainWindow_NewVersion_Download_Button", resourceCulture);
            }
        }
        
        public static string TeamsView_TeamEmptyName_Error {
            get {
                return ResourceManager.GetString("TeamsView_TeamEmptyName_Error", resourceCulture);
            }
        }
        
        public static string TeamsView_DuplicateTeamNames_Error {
            get {
                return ResourceManager.GetString("TeamsView_DuplicateTeamNames_Error", resourceCulture);
            }
        }
        
        public static string InputView_Data_Button {
            get {
                return ResourceManager.GetString("InputView_Data_Button", resourceCulture);
            }
        }
        
        public static string InputView_Add_Button {
            get {
                return ResourceManager.GetString("InputView_Add_Button", resourceCulture);
            }
        }
        
        public static string InputView_AddMember_MenuItem {
            get {
                return ResourceManager.GetString("InputView_AddMember_MenuItem", resourceCulture);
            }
        }
        
        public static string InputView_AddDiscipline_MenuItem {
            get {
                return ResourceManager.GetString("InputView_AddDiscipline_MenuItem", resourceCulture);
            }
        }
        
        public static string InputView_AddToolbarClose_Button {
            get {
                return ResourceManager.GetString("InputView_AddToolbarClose_Button", resourceCulture);
            }
        }
        
        public static string InputView_EmptyInputTable_Label {
            get {
                return ResourceManager.GetString("InputView_EmptyInputTable_Label", resourceCulture);
            }
        }
        
        public static string TeamsView_DeleteAllTeams_Button {
            get {
                return ResourceManager.GetString("TeamsView_DeleteAllTeams_Button", resourceCulture);
            }
        }
        
        public static string TeamsView_DeleteAllTeams_WarningDialog_Message {
            get {
                return ResourceManager.GetString("TeamsView_DeleteAllTeams_WarningDialog_Message", resourceCulture);
            }
        }
    }
}
