//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeamSorting.Lang {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TeamSorting.Lang.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to False.
        /// </summary>
        public static string Bool_False {
            get {
                return ResourceManager.GetString("Bool_False", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to True.
        /// </summary>
        public static string Bool_True {
            get {
                return ResourceManager.GetString("Bool_True", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string CsvErrorDialog_Ok_Button {
            get {
                return ResourceManager.GetString("CsvErrorDialog_Ok_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error loading data from CSV.
        /// </summary>
        public static string CsvErrorDialog_Title {
            get {
                return ResourceManager.GetString("CsvErrorDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error reading data from file.
        /// </summary>
        public static string Data_LoadFromFile_Error {
            get {
                return ResourceManager.GetString("Data_LoadFromFile_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully loaded data from file.
        /// </summary>
        public static string Data_LoadFromFile_Success {
            get {
                return ResourceManager.GetString("Data_LoadFromFile_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error reading value of discipline record: {0}.
        /// </summary>
        public static string Data_LoadMembersData_DisciplineRecord_UnknownError {
            get {
                return ResourceManager.GetString("Data_LoadMembersData_DisciplineRecord_UnknownError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member with name {0} already exists..
        /// </summary>
        public static string Data_LoadMembersData_DuplicateMemberNames_Error {
            get {
                return ResourceManager.GetString("Data_LoadMembersData_DuplicateMemberNames_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found duplicate members in combination constrains.
        /// </summary>
        public static string Data_LoadMembersData_DuplicateMembersInConstarins_Warning {
            get {
                return ResourceManager.GetString("Data_LoadMembersData_DuplicateMembersInConstarins_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found empty member name..
        /// </summary>
        public static string Data_LoadMembersData_EmptyMemberName_Error {
            get {
                return ResourceManager.GetString("Data_LoadMembersData_EmptyMemberName_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found unknown members in combination constrains: {0}.
        /// </summary>
        public static string Data_LoadMembersData_UnknownMemberInConstarins_Error {
            get {
                return ResourceManager.GetString("Data_LoadMembersData_UnknownMemberInConstarins_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong format of discipline record value.
        /// </summary>
        public static string Data_LoadMembersData_WrongDisciplineRecordFormat_Error {
            get {
                return ResourceManager.GetString("Data_LoadMembersData_WrongDisciplineRecordFormat_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error reading data type for discipline {0}
        ///{1}.
        /// </summary>
        public static string Data_ReadDisciplineDataTypes_ReadingError {
            get {
                return ResourceManager.GetString("Data_ReadDisciplineDataTypes_ReadingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown data type &apos;{0}&apos; for discipline &apos;{1}&apos;
        ///Valid values: {2}.
        /// </summary>
        public static string Data_ReadDisciplineDataTypes_WrongDisciplineDataTypes_Error {
            get {
                return ResourceManager.GetString("Data_ReadDisciplineDataTypes_WrongDisciplineDataTypes_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown sort order &apos;{0}&apos; for discipline &apos;{1}&apos;
        ///Valid values: {2}.
        /// </summary>
        public static string Data_ReadDisciplineSortTypes_WrongDisciplineSortOrder_Error {
            get {
                return ResourceManager.GetString("Data_ReadDisciplineSortTypes_WrongDisciplineSortOrder_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team{0}.
        /// </summary>
        public static string Data_TeamName_Template {
            get {
                return ResourceManager.GetString("Data_TeamName_Template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Header contains duplicate columns: .
        /// </summary>
        public static string Data_ValidateCsvHeader_DuplicateColumns_Error {
            get {
                return ResourceManager.GetString("Data_ValidateCsvHeader_DuplicateColumns_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Header doesn&apos;t contain columns: .
        /// </summary>
        public static string Data_ValidateCsvHeader_MissingColumns_Error {
            get {
                return ResourceManager.GetString("Data_ValidateCsvHeader_MissingColumns_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number.
        /// </summary>
        public static string Enum_DisciplineDataType_Number {
            get {
                return ResourceManager.GetString("Enum_DisciplineDataType_Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        public static string Enum_DisciplineDataType_Time {
            get {
                return ResourceManager.GetString("Enum_DisciplineDataType_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asc.
        /// </summary>
        public static string Enum_SortOrder_Asc {
            get {
                return ResourceManager.GetString("Enum_SortOrder_Asc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desc.
        /// </summary>
        public static string Enum_SortOrder_Desc {
            get {
                return ResourceManager.GetString("Enum_SortOrder_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Discipline.
        /// </summary>
        public static string InputView_AddDiscipline_Button {
            get {
                return ResourceManager.GetString("InputView_AddDiscipline_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string InputView_DataGrid_ColumnHeader_Name {
            get {
                return ResourceManager.GetString("InputView_DataGrid_ColumnHeader_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not with.
        /// </summary>
        public static string InputView_DataGrid_ColumnHeader_NotWith {
            get {
                return ResourceManager.GetString("InputView_DataGrid_ColumnHeader_NotWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to With.
        /// </summary>
        public static string InputView_DataGrid_ColumnHeader_With {
            get {
                return ResourceManager.GetString("InputView_DataGrid_ColumnHeader_With", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load data.
        /// </summary>
        public static string InputView_LoadData_Button {
            get {
                return ResourceManager.GetString("InputView_LoadData_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load from file.
        /// </summary>
        public static string InputView_LoadData_FileDialog {
            get {
                return ResourceManager.GetString("InputView_LoadData_FileDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New discipline name.
        /// </summary>
        public static string InputView_NewDiscipline_Watermark {
            get {
                return ResourceManager.GetString("InputView_NewDiscipline_Watermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add member.
        /// </summary>
        public static string InputView_NewMember_Button {
            get {
                return ResourceManager.GetString("InputView_NewMember_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member name.
        /// </summary>
        public static string InputView_NewMember_TextBox_Watermark {
            get {
                return ResourceManager.GetString("InputView_NewMember_TextBox_Watermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove discipline.
        /// </summary>
        public static string InputView_RemoveDiscipline_Button {
            get {
                return ResourceManager.GetString("InputView_RemoveDiscipline_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Member.
        /// </summary>
        public static string InputView_RemoveMember_Button_Tooltip {
            get {
                return ResourceManager.GetString("InputView_RemoveMember_Button_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seed.
        /// </summary>
        public static string InputView_Seed_Watermark {
            get {
                return ResourceManager.GetString("InputView_Seed_Watermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort to teams.
        /// </summary>
        public static string InputView_SortToTeams_Button {
            get {
                return ResourceManager.GetString("InputView_SortToTeams_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string TeamsView_Back_Button {
            get {
                return ResourceManager.GetString("TeamsView_Back_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By going back all teams will be deleted.
        ///Do you want to continue?.
        /// </summary>
        public static string TeamsView_Back_WarningDialog {
            get {
                return ResourceManager.GetString("TeamsView_Back_WarningDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team differences:.
        /// </summary>
        public static string TeamsView_Differences_Label {
            get {
                return ResourceManager.GetString("TeamsView_Differences_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Teams to CSV.
        /// </summary>
        public static string TeamsView_ExportTeamsToCsv_FileDialogTitle {
            get {
                return ResourceManager.GetString("TeamsView_ExportTeamsToCsv_FileDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export teams to CSV.
        /// </summary>
        public static string TeamsView_ExportToCSV_Button {
            get {
                return ResourceManager.GetString("TeamsView_ExportToCSV_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seed.
        /// </summary>
        public static string TeamsView_Seed_Label {
            get {
                return ResourceManager.GetString("TeamsView_Seed_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show member details.
        /// </summary>
        public static string TeamsView_ShowMemberDetails_Label {
            get {
                return ResourceManager.GetString("TeamsView_ShowMemberDetails_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort by name.
        /// </summary>
        public static string TeamsView_SortByMemberName_Label {
            get {
                return ResourceManager.GetString("TeamsView_SortByMemberName_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team is valid: {0}.
        /// </summary>
        public static string TeamsView_TeamIsValid_ToolTip {
            get {
                return ResourceManager.GetString("TeamsView_TeamIsValid_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string WarningDialog_Cancel_Button {
            get {
                return ResourceManager.GetString("WarningDialog_Cancel_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        public static string WarningDialog_Continue_Button {
            get {
                return ResourceManager.GetString("WarningDialog_Continue_Button", resourceCulture);
            }
        }
    }
}
