//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeamSorting.Lang {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources_cs_CZ {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources_cs_CZ() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TeamSorting.Lang.Resources.cs-CZ", typeof(Resources_cs_CZ).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tým{0}.
        /// </summary>
        internal static string Data_TeamName_Template {
            get {
                return ResourceManager.GetString("Data_TeamName_Template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Přidat disciplínu.
        /// </summary>
        internal static string InputView_AddDiscipline_Button {
            get {
                return ResourceManager.GetString("InputView_AddDiscipline_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jméno.
        /// </summary>
        internal static string InputView_DataGrid_ColumnHeader_Name {
            get {
                return ResourceManager.GetString("InputView_DataGrid_ColumnHeader_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nesmí být s.
        /// </summary>
        internal static string InputView_DataGrid_ColumnHeader_NotWith {
            get {
                return ResourceManager.GetString("InputView_DataGrid_ColumnHeader_NotWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Musí být s.
        /// </summary>
        internal static string InputView_DataGrid_ColumnHeader_With {
            get {
                return ResourceManager.GetString("InputView_DataGrid_ColumnHeader_With", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Načíst data.
        /// </summary>
        internal static string InputView_LoadData_Button {
            get {
                return ResourceManager.GetString("InputView_LoadData_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Načíst ze souboru.
        /// </summary>
        internal static string InputView_LoadData_FileDialog {
            get {
                return ResourceManager.GetString("InputView_LoadData_FileDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Název disciplíny.
        /// </summary>
        internal static string InputView_NewDiscipline_Watermark {
            get {
                return ResourceManager.GetString("InputView_NewDiscipline_Watermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Přidat člena.
        /// </summary>
        internal static string InputView_NewMember_Button {
            get {
                return ResourceManager.GetString("InputView_NewMember_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jméno.
        /// </summary>
        internal static string InputView_NewMember_TextBox_Watermark {
            get {
                return ResourceManager.GetString("InputView_NewMember_TextBox_Watermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odstranit disciplínu.
        /// </summary>
        internal static string InputView_RemoveDiscipline_Button {
            get {
                return ResourceManager.GetString("InputView_RemoveDiscipline_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odstranit člena.
        /// </summary>
        internal static string InputView_RemoveMember_Button_Tooltip {
            get {
                return ResourceManager.GetString("InputView_RemoveMember_Button_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Semínko.
        /// </summary>
        internal static string InputView_Seed_Watermark {
            get {
                return ResourceManager.GetString("InputView_Seed_Watermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rozdělit do týmů.
        /// </summary>
        internal static string InputView_SortToTeams_Button {
            get {
                return ResourceManager.GetString("InputView_SortToTeams_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zpět.
        /// </summary>
        internal static string TeamsView_Back_Button {
            get {
                return ResourceManager.GetString("TeamsView_Back_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vrácením zpět budou všechny týmy smazány.
        ///Chcete pokračovat?.
        /// </summary>
        internal static string TeamsView_Back_WarningDialog {
            get {
                return ResourceManager.GetString("TeamsView_Back_WarningDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rozdíly mezi týmy:.
        /// </summary>
        internal static string TeamsView_Differences_Label {
            get {
                return ResourceManager.GetString("TeamsView_Differences_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exportovat týmy do CSV.
        /// </summary>
        internal static string TeamsView_ExportTeamsToCsv_FileDialogTitle {
            get {
                return ResourceManager.GetString("TeamsView_ExportTeamsToCsv_FileDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exportovat týmy do CSV.
        /// </summary>
        internal static string TeamsView_ExportToCSV_Button {
            get {
                return ResourceManager.GetString("TeamsView_ExportToCSV_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Semínko.
        /// </summary>
        internal static string TeamsView_Seed_Label {
            get {
                return ResourceManager.GetString("TeamsView_Seed_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zobrazit detaily členů.
        /// </summary>
        internal static string TeamsView_ShowMemberDetails_Label {
            get {
                return ResourceManager.GetString("TeamsView_ShowMemberDetails_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seřadit podle jména.
        /// </summary>
        internal static string TeamsView_SortByMemberName_Label {
            get {
                return ResourceManager.GetString("TeamsView_SortByMemberName_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tým je platný: {0}.
        /// </summary>
        internal static string TeamsView_TeamIsValid_ToolTip {
            get {
                return ResourceManager.GetString("TeamsView_TeamIsValid_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zrušit.
        /// </summary>
        internal static string WarningDialog_Cancel_Button {
            get {
                return ResourceManager.GetString("WarningDialog_Cancel_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pokračovat.
        /// </summary>
        internal static string WarningDialog_Continue_Button {
            get {
                return ResourceManager.GetString("WarningDialog_Continue_Button", resourceCulture);
            }
        }
    }
}
