# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Create release

on:
  push:
    tags:
    - 'v*.*.*'

env:
  PROJECT_PATH: TeamSorting/TeamSorting.csproj

jobs:
  build:
    permissions:
      contents: write
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Build win
      run: dotnet publish ${{ env.PROJECT_PATH }} -c Release -r win-x64 --self-contained true /p:AssemblyName=TeamSorting-win-x64 /p:PublishSingleFile=true /p:IncludeNativeLibrariesForSelfExtract=true --output bin/win-x64
    - name: Build linux
      run: dotnet publish ${{ env.PROJECT_PATH }} -c Release -r linux-x64 --self-contained true /p:AssemblyName=TeamSorting-linux-x64 /p:PublishSingleFile=true /p:IncludeNativeLibrariesForSelfExtract=true --output bin/linux-x64
    - name: Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "bin/win-x64/TeamSorting-win-x64.exe,bin/linux-x64/TeamSorting-linux-x64"
        bodyFile: "CHANGELOG.md"
        draft: true
